### ISSUE TITLE
crash when navigate to settings while using position/speed/course

### ISSUE THREAD

**Issue by bfv** [bfv/sailert#9]
When the app is recording position/speed/course on the home page and one navigates to the settings page (via SideDrawer) the app crashes.

**Comment by bfv** [comment]
```An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onLocationChanged failed

[object Object]
File: "file:///data/data/io.bfv.sailert/files/app/tns_modules/rxjs/Subscriber.js, line: 227, column: 12

StackTrace: 
        Frame: function:'SafeSubscriber.__tryOrUnsub', file:'file:///data/data/io.bfv.sailert/files/app/tns_modules/rxjs/Subscriber.js', line: 227, column: 13
        Frame: function:'SafeSubscriber.next', file:'file:///data/data/io.bfv.sailert/files/app/tns_modules/rxjs/Subscriber.js', line: 172, column: 22
        Frame: function:'Subscriber._next', file:'file:///data/data/io.bfv.sailert/files/app/tns_modules/rxjs/Subscriber.js', line: 125, column: 26
        Frame: function:'Subscriber.next', file:'file:///data/data/io.bfv.sailert/files/app/tns_modules/rxjs/Subscriber.js', line: 89, column: 18
        Frame: function:'Subject.next', file:'file:///data/data/io.bfv.sailert/files/app/tns_modules/rxjs/Subject.js', line: 55, column: 25
        Frame: function:'EventEmitter.emit', file:'file:///data/data/io.bfv.sailert/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4090, column: 80
        Frame: function:'NgZone.triggerError', file:'file:///data/data/io.bfv.sailert/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4451, column: 80
        Frame: function:'onHandleError', file:'file:///data/data/io.bfv.sailert/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4412, column: 27
        Frame: function:'ZoneDelegate.handleError', file:'file:///data/data/io.bfv.sailert/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 194, column: 39
        Frame: function:'Zone.runGuarded', file:'file:///data/data/io.bfv.sailert/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 100, column: 44
        Frame: function:'', file:'file:///data/data/io.bfv.sailert/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 73, column: 29
        Frame: function:'onLocationChanged', file:'file:///data/data/io.bfv.sailert/files/app/tns_modules/nativescript-geolocation/nativescript-geolocation.js', line: 23, column: 17


        at com.tns.Runtime.callJSMethodNative(Native Method)
        at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
        at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
        at com.tns.Runtime.callJSMethod(Runtime.java:1047)
        at com.tns.Runtime.callJSMethod(Runtime.java:1028)
        at com.tns.Runtime.callJSMethod(Runtime.java:1018)
        at com.tns.gen.android.location.LocationListener.onLocationChanged(android.location.LocationListener.java)
        at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:285)
        at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
        at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:230)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)```

**Comment by bfv** [comment]
Every subscribe on an Observable needs an Unsubscribe in ngOnDestroy
